export const getSkillIcon = (skill: string) => {
  const devicon = (name: string, version: string = 'original') => `https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/${name}/${name}-${version}.svg`;
  const simpleicon = (slug: string, color?: string) => `https://cdn.simpleicons.org/${slug}${color ? `/${color}` : ''}`;

  const iconMap: Record<string, string> = {
    'Go': devicon('go'),
    'TypeScript': devicon('typescript'),
    'Dart': devicon('dart'),
    'Java': devicon('java'),
    'Bash': devicon('bash'),
    'Lua': devicon('lua'),
    'C': devicon('c'),
    'JavaScript': devicon('javascript'),
    'SQL': simpleicon('postgresql'),
    'CQL': simpleicon('apachecassandra'),
    'Gin': simpleicon('gin'),
    'Fiber': simpleicon('gofiber'),
    'React': devicon('react'),
    'React.js': devicon('react'),
    'React Native': devicon('react'),
    'Next.js': simpleicon('nextdotjs', 'white'),
    'Node.js': devicon('nodejs'),
    'NestJS': devicon('nestjs'),
    'Express.js': simpleicon('express', 'white'),
    'Express': simpleicon('express', 'white'),
    'Tailwind CSS': devicon('tailwindcss'),
    'Expo': simpleicon('expo', 'white'),
    'Linux': devicon('linux'),
    'CI/CD': devicon('githubactions'),
    'GraphQL': devicon('graphql', 'plain'),
    'REST': devicon('nodejs'),
    'Hono.js': simpleicon('hono'),
    'ElysiaJS': simpleicon('elysia'),
    'Docker': devicon('docker'),
    'Kubernetes': devicon('kubernetes', 'plain'),
    'Terraform': devicon('terraform'),
    'Ansible': devicon('ansible'),
    'AWS CDK': simpleicon('amazonwebservices'),
    'AWS Lambda': simpleicon('awslambda'),
    'Azure Functions': simpleicon('azurefunctions'),
    'AWS SAM': simpleicon('amazonwebservices'),
    'Serverless Framework': simpleicon('serverless'),
    'AWS': devicon('amazonwebservices', 'original-wordmark'),
    'Azure': devicon('azure'),
    'S3': simpleicon('amazons3'),
    'CloudFront': simpleicon('amazoncloudfront'),
    'CloudWatch': simpleicon('amazoncloudwatch'),
    'EC2': simpleicon('amazonec2'),
    'SSM': simpleicon('amazonwebservices'),
    'PostgreSQL': devicon('postgresql'),
    'DynamoDB': simpleicon('amazondynamodb'),
    'MongoDB': devicon('mongodb'),
    'CockroachDB': simpleicon('cockroachdb'),
    'Cassandra': devicon('apachecassandra'),
    'Redis': devicon('redis'),
    'RabbitMQ': devicon('rabbitmq'),
    'Kafka': devicon('apachekafka'),
    'Firebase': devicon('firebase', 'plain'),
    'Appwrite': devicon('appwrite'),
    'Supabase': devicon('supabase'),
    'LangChain': simpleicon('langchain'),
    'Langflow': simpleicon('langchain'),
    'OpenAI API': simpleicon('openai', 'white'),
    'RAG': simpleicon('openai', 'white'),
    'Crew AI': simpleicon('robot'),
    'Microservices': devicon('docker'),
    'gRPC': simpleicon('grpc'),
    'REST APIs': devicon('nodejs'),
    'CI/CD Pipelines': devicon('githubactions'),
    'Web Scraping': devicon('python'),
    'Flutter': devicon('flutter'),
    'n8n': simpleicon('n8n'),
    'Git': devicon('git'),
    'MCP': simpleicon('anthropic', 'white'),
  };

  return iconMap[skill] || null;
};
